name: Build and Release

on:
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: "Upload Artifact"
        default: false
        required: false
        type: boolean
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.2.2
        with:
          path: main
          submodules: recursive

      - name: Caching brew dependencies
        id: brew_cache
        uses: tecolicom/actions-use-homebrew-tools@v1.2
        with:
          tools: ldid xz make
          cache: yes

      - name: Install Dependencies
        if: steps.brew_cache.outputs.cache-hit != 'true'
        run: brew install ldid xz make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.2.2
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: Caching SDK
        id: SDK
        uses: actions/cache@v4.2.0
        env:
          cache-name: iOS-13.7-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
      
      - name: Download iOS 13.7 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git && cd sdks
          git sparse-checkout set --no-cone iPhoneOS13.7.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          make package FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
        env:
          THEOS: ${{ github.workspace }}/theos
      
      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: jetsamctl
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT: ${{ inputs.create_release }}
        with:
          files: main/packages/*.deb
          draft: ${{ env.DRAFT }}
